### ISSUE TITLE
Units are incorrectly reported as "isAttacking" and "isAttackFrame" when holding position

### ISSUE THREAD

**Issue by krasi0** [bwapi/bwapi#525]
Although there are no targets to shoot at nearby, 
its animState equals BW::Anims::GndAttkRpt in UnitUpdate.cpp:210

**Comment by heinermann** [comment]
This happens after the Battlecruiser fires at a target.

**Comment by heinermann** [comment]
I actually have no clue how to deal with it. Will have to go back to the basics and poll all relevant and unknown fields of the Image, Sprite, and Unit structures.

**Comment by heinermann** [comment]
Some progress on dealing with issues like this one.
![screenshot from 2015-01-07 15 01 06](https://cloud.githubusercontent.com/assets/1966366/5652384/17c4704a-967e-11e4-981e-eaf230c6a990.png)

**Comment by heinermann** [comment]
Confirmed happens with other units.

I actually don't really see any real difference besides the anim. This is really weird. I have no idea how to deal with it.

![screenshot from 2015-01-11 12 03 54](https://cloud.githubusercontent.com/assets/1966366/5695999/45322e82-998a-11e4-8217-0eaed28b3f7d.png)
![screenshot from 2015-01-11 12 00 57](https://cloud.githubusercontent.com/assets/1966366/5696000/4ac5a932-998a-11e4-90d8-81ff18d637a7.png)

**Comment by krasi0** [comment]
I use a workaround if the target is still alive / in range

**Comment by heinermann** [comment]
This might not actually be a workaround, it may be the actual solution.

**Comment by heinermann** [comment]
Fixed in abce0dc. Please verify.

**Comment by krasi0** [comment]
It seems like the issue is still reproducible. A Battlecruiser in holdPosition with no target within attack range is reported to have isAttackFrame() == true

**Comment by heinermann** [comment]
Unable to repro. Need steps.

**Comment by krasi0** [comment]
Maybe the main issue has really been fixed. 
Now, the situation is that a BC is reported in attackFrame() a frame or two after its shooting target has been destroyed (does not exist anymore), but I don't think that's a big issue. Do you think, that we should improve the fix to also check if the target exists or...?

**Comment by heinermann** [comment]
I just tested this, and `getOrderTarget()` will return a unit that doesn't exist for **exactly** one frame after it's killed. It happens normally regardless of the order and for every unit I've tested it with (Marines, Ghosts, Wraiths, Battlecruisers, etc).

This is most likely Broodwar behaviour.

**Comment by heinermann** [comment]
Yeah, `isAttackFrame()` and `isAttacking()` are also true for **exactly** one frame after the target has been killed.

**Comment by krasi0** [comment]
Well, it doesn't matter if it's only one frame or more. It is still wrong
and screws up my bot logic... I have asserts for such cases

**Comment by heinermann** [comment]
I think I've dealt with it in #578.
